apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{.Values.runlabel}}
  name: demo-cte-dpg-secrets-api
spec:
  template:
     metadata:
        name: {{.Values.deployment.name}}
        labels:
          run: {{.Values.runlabel}}
     spec:
        containers:
          - image: {{.Values.deployment.appimage}}
            imagePullPolicy: IfNotPresent
            name: {{.Values.deployment.appimagename}}
            volumeMounts:
              - mountPath: "/data"
                name: test-vol

  replicas: {{.Values.deployment.replicas}}
  selector:
      matchLabels:
        run: {{.Values.runlabel}}