apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{.Values.runlabel}}
  name: appserver-deployment
spec:
  template:
     metadata:
        name: {{.Values.deployment.name}}
        labels:
          run: {{.Values.runlabel}}
     spec:
        containers:
          - image: {{.Values.deployment.apiimage}}
            imagePullPolicy: IfNotPresent
            name: {{.Values.deployment.apiimagename}}
            ports:
            - containerPort: 8080
          - image: {{.Values.deployment.dpgimage}}
            imagePullPolicy: IfNotPresent
            name: {{.Values.deployment.dpgimagename}}
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8990
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /liveness
                port: 8990
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
            env:
             - name: KMS
               valueFrom:
                 configMapKeyRef:
                   name: {{.Values.dpg_configuration.configmapname}}
                   key: KMS
             - name: CERT_PATH
               valueFrom:
                  secretKeyRef:
                    name: {{.Values.dpg_configuration.secretname}} 
                    key: server.crt
             - name: KEY_PATH
               valueFrom:
                  secretKeyRef:
                    name: {{.Values.dpg_configuration.secretname}}
                    key: server.key
             - name: TLS_ENABLED
               valueFrom:
                  configMapKeyRef:
                    name: {{.Values.dpg_configuration.configmapname}}
                    key: TLS_ENABLED
             - name: REG_TOKEN
               valueFrom:
                  configMapKeyRef:
                    name: {{.Values.dpg_configuration.configmapname}}
                    key: REG_TOKEN
             - name: DESTINATION_URL
               valueFrom:
                  configMapKeyRef:
                    name: {{.Values.dpg_configuration.configmapname}}
                    key: DESTINATION_URL       
  replicas: {{.Values.deployment.replicas}}
  selector:
      matchLabels:
        run: {{.Values.runlabel}}
---
apiVersion: v1
data:
  server.crt: {{.Values.dpg_configuration.servercrt}}
  server.key: {{.Values.dpg_configuration.serverkey}}
kind: Secret
metadata:
  name: {{.Values.dpg_configuration.secretname}}
type: Opaque
---

apiVersion: v1
items:
  - apiVersion: v1
    data:
      TLS_ENABLED: {{.Values.dpg_configuration.tlsenabled | quote}}
      KMS: {{.Values.dpg_configuration.kms}}
      REG_TOKEN:  {{.Values.dpg_configuration.reg_token}}
      DESTINATION_URL:  {{.Values.dpg_configuration.appurl}}
    kind: ConfigMap
    metadata:
      name: {{.Values.dpg_configuration.configmapname}}
  - apiVersion: v1
    data:
      CM_URL: {{.Values.api_configuration.kms}}
      CM_USERNAME:  {{.Values.api_configuration.kms_username}}
      CM_PASSWORD:  {{.Values.api_configuration.kms_password}}
      CM_USER_SET_ID: {{.Values.api_configuration.userSetID}}
    kind: ConfigMap
    metadata:
      name: {{.Values.api_configuration.configmapname}}
kind: List
metadata: