apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{.Values.service.name}}
              port:
                number: {{.Values.service.apiPort}}
        - path: /dpg
          pathType: Prefix
          backend:
            service:
              name: {{.Values.service.name}}
              port: 
                number: {{.Values.service.dpgPort}}